main/urls.py
from django.conf.urls import url, include
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'main'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^location-base/$', views.base, name='base'),
    url(r'^update_photos_list/$', views.update_photos, name='update_photos_list'),
    url(r'^blog/$', views.blog, name='blog'),
    url(r'^fav/$', views.favourite, name='fav'),
    url(r'^blog/(?P<alias>[a-zA-Z0-9\-\_]+)/$', views.blog_item, name='blog_item'),
    url(r'^location-base/(?P<alias>[a-zA-Z0-9\-\_]+)/$', views.card, name='card'),
    url(r'^ajax/$', views.ajax, name='ajax'),
    url(r'^robots\.txt$', views.robots, name='robots'),
    url(r'^(?P<alias>[0-9A-Za-z\-]+)/$', views.textpage, name='textpage'),
    url(r'^get_fields/$', views.get_fields, name='get_fields'),
    url(r'^sitemap\.xml/$', views.sitemap_xml, name='sitemap'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings as django_settings
from ckeditor.fields import RichTextField
from django.contrib.postgres.fields import JSONField
from django.urls import reverse
from datetime import datetime
import uuid
import os
import shutil
import re

from multiselectfield import MultiSelectField

LOCATION_TYPE = (
    (1, 'квартиры'),
    (2, 'дома'),
    (3, 'пентхаусы'),
    (4, 'дома отдыха'),
    (5, 'гостиницы и отели'),
    (6, 'дачи'),
    (7, 'усадьбы'),
    (8, 'мансарды'),
    (9, 'магазины'),
    (10, 'больница и клиники'),
    (11, 'школы'),
    (12, 'детские сады'),
    (13, 'салоны красоты'),
    (14, 'клубы и бары'),
    (15, 'рестораны и кафе'),
    (16, 'заброшенные здания'),
    (17, 'институты и академии'),
    (18, 'лофты'),
    (19, 'гаражи'),
    (20, 'автомойки и сервисы'),
    (21, 'подъезды'),
    (22, 'дворцы культуры'),
    (23, 'склады'),
    (24, 'павильоны'),
    (25, 'аэропорты и вокзалы'),
    (26, 'офисы'),
    (27, 'мастерские'),
    (28, 'почта'),
    (29, 'спорт'),
    (30, 'выставочные помещения'),
    (31, 'парковки'),
    (32, 'крыши и чердаки'),
    (33, 'подвалы'),
    (34, 'отделения полиции'),
    (35, 'храмы'),
    (36, 'морги'),
    (37, 'лес'),
    (38, 'поле'),
    (39, 'двор'),
    (40, 'улица'),
    (41, 'водоем'),
    (42, 'парк'),
    (43, 'кладбище'),
    (44, 'яхты'),
    (45, 'самолеты'),
    (46, 'вертолеты'),
    (47, 'автомобили')
)

ROOM_TYPE = (
    (1, 'кухня'),
    (2, 'гостиная'),
    (3, 'кабинет'),
    (4, 'библиотека'),
    (5, 'детская'),
    (6, 'ванная'),
    (7, 'спальня'),
    (8, 'бассейн'),
    (9, 'сауна'),
    (10, 'гараж'),
    (11, 'веранда'),
    (12, 'новостройка'),
    (13, 'другое')
)

STYLE_TYPE = (
    (1, 'современный'),
    (2, 'советский'),
    (3, 'классический'),
    (4, 'хай-тек'),
    (5, 'деревенский'),
    (6, 'исторический'),
    (7, 'скандинавский'),
    (8, 'лофт'),
    (9, 'модерн'),
    (10, 'эко'),
    (11, 'минимализм'),
    (12, 'эклектика'),
    (13, 'азиатский'),
    (14, 'готика')
)

LOCATION_PLACE = (
    (0, 'Не указано'),
    (1, 'ЮАО'),
    (2, 'ЮЗАО'),
    (3, 'ЗАО'),
    (4, 'СЗАО'),
    (5, 'САО'),
    (6, 'СВАО'),
    (7, 'ВАО'),
    (8, 'ЮВАО'),
    (9, 'ЦАО'),
    (10, 'НАО'),
    (11, 'ТАО'),
    (12, 'Московская область'),
    (13, 'Другое'),
    (14, 'Киевское шоссе'),
    (15, 'Калужское шоссе'),
    (16, 'Новорижское шоссе'),
    (17, 'Симферопольское шоссе'),
    (18, 'Рублево-Успенское шоссе'),
    (19, 'Минское шоссе')
)


class Page(models.Model):
    class Meta:
        abstract = True

    alias = models.SlugField(max_length=200, verbose_name=u"Url")
    og_title = models.CharField(max_length=200, verbose_name="OG Title", null=True, blank=True)
    og_description = models.TextField(max_length=2000, verbose_name="OG Description", null=True, blank=True)
    og_type = models.CharField(max_length=200, verbose_name="OG Type", null=True, blank=True)
    og_type_pb_time = models.DateField(default=datetime.now(), verbose_name=u"Время публикации")
    og_type_author = models.CharField(max_length=200, verbose_name="OG author", null=True, blank=True)
    seo_h1=models.CharField(max_length=200, verbose_name="H1", null=True, blank=True)
    seo_title=models.CharField(max_length=200, verbose_name="Title", null=True, blank=True)
    seo_description=models.CharField(max_length=500, verbose_name="Description", null=True, blank=True)
    seo_keywords=models.CharField(max_length=500, verbose_name="Keywords", null=True, blank=True)
    menutitle=models.CharField(max_length=200, verbose_name=u"Название в меню", null=True, blank=True, help_text='Не обязательно')
    content = RichTextField(config_name='default', null=True, blank=True)
    
class TextPage(Page):
    class Meta:
        verbose_name = u"Текстовая страница"
        verbose_name_plural = u"Страницы"
        
    name = models.CharField(max_length=200, verbose_name=u"Название")
    alias = models.SlugField(max_length=200, verbose_name=u"Url", unique=True)

    def get_absolute_url(self):
        if self.alias == 'index':
            return '/'
        else:
            return reverse('main:textpage', args=[self.alias])
    
    def __str__(self):
        return self.name
        
class BlogPage(Page):
    class Meta:
        verbose_name = u"Страница блога"
        verbose_name_plural = u"Блог"
    
    name=models.CharField(max_length=200, verbose_name=u"Название")
    datetime = models.DateTimeField(verbose_name=u"Дата публикации", auto_now_add=True, editable=False)
    image = models.ImageField(verbose_name=u"Првеью Блога", null=True, blank=True)
    
    def __str__(self):
        return self.name
        
class Location(Page):
    class Meta:
        verbose_name = u"Локацию"
        verbose_name_plural = u"Локации"
        
    name = models.CharField(max_length=200, verbose_name=u"Название")
    area = models.CharField(max_length=200, verbose_name=u"Площадь", null=True, blank=True)
    number = models.IntegerField(verbose_name=u"Номер локации", null=True, blank=True)
    to_main = models.BooleanField(default=False, verbose_name=u"Актуальная локация")
    loc_descr = models.TextField(verbose_name="Описание локации", null=True, blank=True)
    loc_type = models.PositiveSmallIntegerField(verbose_name='Тип локации', choices=LOCATION_TYPE, default=1)
    room = MultiSelectField(verbose_name='Помещение', choices=ROOM_TYPE, max_choices=20, max_length=30, default=ROOM_TYPE[12][0])
    style = models.PositiveSmallIntegerField(verbose_name='Стиль', default=1, choices=STYLE_TYPE)
    addres = models.PositiveSmallIntegerField(verbose_name='Местоположение', default=0, choices=LOCATION_PLACE)
    address_custom = models.CharField(max_length=200, verbose_name=u"Местоположение кастом", null=True, blank=True, help_text='Если заполнено то учитывается только оно')
    alias = models.SlugField(max_length=200, verbose_name=u"Url", unique=True)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        try:
            if not [i for i in os.listdir(os.getcwd() + '/media/locations') if re.search('^{}_.*'.format(self.pk), i) != None]:
                os.mkdir(os.getcwd() + '/media/locations/{}_{}'.format(self.pk, self.alias))
        except:
            pass
            
    def delete(self, *args, **kwargs):
        shutil.rmtree(os.getcwd() + '/media/locations/{}_{}'.format(self.pk, self.alias))
        super().delete(*args, **kwargs)
        
    
    def get_first_item(self):
        try:
            return self.location_photos.all().order_by('ordering')[0]
        except:
            None

    def get_absolute_url(self):
        return reverse('main:card', args=[self.alias])

    def __str__(self):
        return self.name
        
class LocationPhoto(models.Model):
    class Meta:
        verbose_name = u"Фотографии локаций"
        verbose_name_plural = u"Фотография локации"
        ordering = ['ordering']
        
    image = models.ImageField(verbose_name=u"Фото", upload_to='locations')
    name = models.CharField(max_length=200, verbose_name=u"Название", null=True, blank=True)
    ordering = models.IntegerField(verbose_name=u"Порядок", default=200)
    location = models.ForeignKey(Location, verbose_name=u"Локация", related_name="location_photos", on_delete=models.CASCADE)
    
    def delete(self, *args, **kwargs):
        os.remove('/home/pweb/location' + self.image.url)
        super().delete(*args, **kwargs)
    
    def __str__(self):
        return self.location.name

class Member(models.Model):
    class Meta:
        verbose_name = u"Участники команды"
        verbose_name_plural = u"Участник команды"

    name = models.CharField(max_length=200, verbose_name=u"Название")
    image = models.ImageField(verbose_name=u"Фото")
    phone = models.CharField(max_length=200, verbose_name=u"Телефон")
    email = models.CharField(max_length=200, verbose_name=u"Емайл")

    def __str__(self):
        return self.name

class Session(models.Model):

    class Meta:
        verbose_name = u"Сессии"
        verbose_name_plural = u"Сессия"

    token = models.UUIDField(default=uuid.uuid4, editable=False)
    favourite = JSONField(verbose_name=u"Избранное", default=list, null=True, blank=True)

    @classmethod
    def set_session(cls, request):
        # Инициализация сессии пользователя
        cart = cls.objects.filter(token=request.session.get(django_settings.CART_SESSION_ID)).first()
        if not cart:
            # Сохраняем сессию
            cart = cls.objects.create(token=str(uuid.uuid4()))
            request.session[django_settings.CART_SESSION_ID] = cart.token

        return cart

    get_session = set_session

    def __str__(self):
        return self.token
        
class Partners(Page):
    class Meta:
        verbose_name = u"Партнер"
        verbose_name_plural = u"Партнеры"
        
    image = models.ImageField(verbose_name=u"Фото", upload_to='partners')
    name = models.CharField(max_length=200, verbose_name=u"Название", null=True, blank=True)
    url = models.CharField(max_length=200, verbose_name=u"Url партнера", null=True, blank=True)

    def __str__(self):
        return self.name


class Service(models.Model):
    class Meta:
        verbose_name = u"Услуга"
        verbose_name_plural = u"Услуги"

    name = models.CharField(max_length=200, verbose_name=u"Название")
    description = models.TextField(verbose_name="Описание", null=True, blank=True)

    def __str__(self):
        return self.name


class Popular(models.Model):
    class Meta:
        verbose_name = u"Популярный запрос"
        verbose_name_plural = u"Популярные запросы"

    name = models.CharField(max_length=200, verbose_name=u"Название")
    url = models.CharField(max_length=200, verbose_name=u"Url партнера", help_text="https://locationbook.ru/location-base/?room=1")

    def __str__(self):
        return self.name

class TextVariable(models.Model):
    class Meta:

templates/blog.html
{% extends "base.html" %}
{% block seo_titles %}
    <title>{% if data.seo_title %}{{ data.seo_title }}{% else %}{{ data.name }}{% endif %}</title>
    <meta name="description" content="{% if data.seo_description %}{{ data.seo_description }}{% else %}{{ data.name }}{% endif %}">
    <meta name="keywords" content="{% if data.seo_keywords %}{{ data.seo_keywords }}{% else %}{{ data.name }}{% endif %}">
{% endblock %}
{% block content %}

<div class="wrapper">
    <div class="breadcrumbs">
        <a href="/">Главная</a> /
        <span>Блог</span>
    </div>
    <div class="blog">
        {% for i in blog_items %}
            <article class="blog__el">
                <a href="{% url 'main:blog_item' i.alias %}"><div class="blog__img" style="background-image: url({% if i.image %}{{ i.image.url }}{% else %}/static/img/main_slider__img.jpg){% endif %};"></div></a>
                <div class="blog__date">{{ i.datetime|date:"d/m/Y" }}</div>
                <h2 class="blog__h2">{{ i.name }}</h2>
                <div class="blog__text">{{ i.content|safe|striptags|truncatechars:100 }}</div>
                <a href="{% url 'main:blog_item' i.alias %}" class="blog__link">читать далее ↓</a>
            </article>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/card.html
{% extends "base.html" %}
{% block seo_titles %}
    <title>{% if data.seo_title %}{{ data.seo_title }}{% else %}{{ data.name }} | Locationbook - сервис по подбору локаций и объектов для съемок{% endif %}</title>
    <meta name="description" content="{% if data.seo_description %}{{ data.seo_description }}{% else %}{{ data.name }} | Locationbook - сервис по подбору локаций и объектов для съемок{% endif %}">
    <meta name="keywords" content="{% if data.seo_keywords %}{{ data.seo_keywords }}{% else %}объекты для съемок, аренда помещений для съемок, аренда локаций для съемок, лоакции для кино, кинообъекты, локации для съемок кино{% endif %}">
{% endblock %}
{% block more_css %}

    <link rel="stylesheet" href="/static/js/libs/fancybox/jquery.fancybox.css">

{% endblock %}

{% block content %}

<div class="wrapper">
    <div class="breadcrumbs">
        <a href="/">Главная</a> /
        <a href="/location-base/">База</a> /
        <span>{{ data.name }}</span>
    </div>
</div>
<div class="card">
    <div class="card__left">
        <h1 class="card__h1">Два дома по 500 м2 каждый на участке с ландшафтным дизайном</h1>
        <div class="card__number">
            <span>{% if data.number %}{{ data.number }}{% else %}{{ data.id }}{% endif %}</span>
            номер лота
        </div>
        <div class="card__wrp card__wrp-1 active">
            <div class="card_nav">
                <div class="card_nav__nav active">Описание</div>
                <div class="card_nav__nav">Характеристики</div>
                <div class="card_nav__nav">Скачать</div>
            </div>
            <div class="card__row card__row-text card__show card__show-1 active">{{ data.loc_descr }}</div>
            <div class="card__row card__row-small card__row-border card__show card__show-2">
                <div class="card__wp">
                    <div>Площадь</div>
                    <div>Тип</div>
                    <div>Стиль</div>
                    <div>Место</div>
                </div>
                <div class="card__wp">
                    <div>500 м</div>
                    <div>Дом</div>
                    <div>Современный</div>
                    <div>Рассказовка</div>
                </div>
            </div>
            <div class="card__row card__row-small card__row-click">
                {% comment %} <ul class="card__ul">
                    {% for i in data.location_photos.all %}
                    <li>{% if i.name %}{{ i.name }}{% else %}Фотография{% endif %}</li>
                    {% endfor %}
                </ul> {% endcomment %}
                <div class="card__gal">
                    <span>Скрыть галлерею →</span>
                    <span>Показать галлерею ×</span>
                </div>
            </div>
            <div class="card__row card__row-last">
                <div class="card__lft">
                    <div class="card__show-dwnld card__show card__show-3">
                        <div class="card__txt">Скачать фото:</div>
                        <div class="card__downloads">
                            <a href="#" class="card__download">PDF</a>
                            <a href="#" class="card__download">JPEG</a>
                        </div>
                    </div>
                    <div class="card_fav add_to_fav{% if data.pk in session.favourite %} active{% endif %}" data-id="{{ data.id }}">
                        <div class="card_fav__img"></div>
                        <div class="card_fav__txt"><span>+ Добавить</span> <span>Доблено</span> в избранное</div>
                    </div>
                </div>
                <div class="card__buttons">
                    <!--<a href="tel:{{ siteinfo.phone }}" class="card__button">Позвонить {{ siteinfo.phone }}</a>-->
                    <div class="card__button card__button-show">Отправить запрос</div>
                </div>
            </div>
        </div>
        <form class="card__form card__wrp card__wrp-2" onsubmit="return false">
            <div class="close close-card"></div>
            <input class="card__input" id="name" name="name" type="text" placeholder="Имя">
            <input class="card__input card__input-small card__input-border" id="phone" name="phone" type="text" placeholder="Номер телефона">
            <input class="card__input card__input-small" id="email" name="email" type="email" placeholder="E-mail">
            <input class="card__input" id="project" name="project" type="text" placeholder="Название проекта">
            <textarea class="card__textarea" id="comment" name="comment" placeholder="Комментарий"></textarea>
            <div class="card__row card__row-form">
                <div class="card_fav">
                    <div class="card_fav__img"></div>
                    <div class="card_fav__txt">+ Добавить в избранное</div>
                </div>
                <input class="card__button card__button-submit" id="card__wrp__submit" name="card__wrp__submit" type="submit" value="Отправить запрос">
            </div>
        </form>
    </div>
    <div class="card__right">
        <div class="card__tile active">
            <div class="card__tl">
                {% for i in data.location_photos.all %}
                    <div class="card__img" style="background-image: url(//locationbook.ru{{ i.image.url }});" title="{{ data.name }}"></div>
                    {% if forloop.counter|divisibleby:"9" %}
                        </div>
                        <div class="card__tl">
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <div class="card__slider">
            <div class="close close-card__slider"></div>
            <div class="card__w">
                {% for i in data.location_photos.all %}
                    <a href="//locationbook.ru{{ i.image.url }}" class="card__slide fancybox" style="background-image: url(//locationbook.ru{{ i.image.url }});" title="{{ data.name }}">
                        <div class="card__dsc">{% if i.name %}{{ i.name }}{% endif %}</div>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block more_js %}

    <script src="/static/js/libs/fancybox/jquery.fancybox.js"></script>
    <script>
        $(document).ready(function () {
            $('#card__wrp__submit').click(function () {
                params = {
                    name: $('.card__form [name=name]').val(),
                    phone: $('.card__form [name=phone]').val(),
                    email: $('.card__form [name=email]').val(),
                    project: $('.card__form [name=project]').val(),
                    comment: $('.card__form [name=comment]').val(),
                    location: $('h1.card__h1').text(),
                }
                if( params['name'] != "" && params['phone'] != "" ){
                    $('.big_loader').addClass('active')
                    $.ajax({
                        url: '/ajax/',
                        method: "POST",
                        data: {type: 'book_room', params : params, csrfmiddlewaretoken: getCookie('csrftoken')},
                        success: function (data, textStatus){
                            $('.big_loader').removeClass('active')
                            alert('отправлено')
                            $('.card__form .close.close-card').trigger('click')
                            $('.card__form [name=name]').val('')
                            $('.card__form [name=phone]').val('')
                            $('.card__form [name=email]').val('')
                            $('.card__form [name=project]').val('')
                            $('.card__form [name=comment]').val('')
                        }
                    })
                }
            })
        })
    </script>
{% endblock %}

templates/fav.html
{% extends "base.html" %}
{% block content %}
<div class="wrapper">
    <div class="breadcrumbs">
        <a href="/">Главная</a> /
        <span>Избранное</span>
    </div>
</div>
<div class="wrapper wrapper-fav">
    <div class="fav__wrp">
        <div class="fav__row">
            {% for l in locations %}
                <div class="fav__card">
                    <div class="fav__block fav__block-left">
                        <a href="{% url 'main:card' l.alias %}" class="fav__title">{{ l.name }}</a>
                        <div class="fav__counter">{{ l.number }}</div>
                        <div class="fav_desc">
                            <div class="fav_desc__col">
                                <div>Площадь</div>
                                <div>Тип</div>
                                <div>Стиль</div>
                                <div>Место</div>
                            </div>
                            <div class="fav_desc__col">
                                <div>500 м</div>
                                <div>Дом</div>
                                <div>Современный</div>
                                <div>Рассказовка</div>
                            </div>
                        </div>
                        <div class="card__txt">Скачать фото:</div>
                        <div class="card__downloads">
                            <a href="#" class="card__download">PDF</a>
                            <a href="#" class="card__download">JPEG</a>
                        </div>
                    </div>
                    <div class="fav__block fav__block-right">
                        <div class="fav__fav{% if l.pk in session.favourite %} active{% endif %}" data-id="{{ l.pk }}"></div>
                        <a href="{% url 'main:card' l.alias %}" class="fav__img" style="background-image: url(//locationbook.ru/media/{{ l.get_first_item.image }});"></a>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:2 and not forloop.last %}
                </div>
                <div class="fav__row">
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/search.html
{% extends "base.html" %}
{% block seo_titles %}
    <title>{% if data.seo_title %}{{ data.seo_title }}{% else %}{{ data.name }}{% endif %}</title>
    <meta name="description" content="{% if data.seo_description %}{{ data.seo_description }}{% else %}{{ data.name }}{% endif %}">
    <meta name="keywords" content="{% if data.seo_keywords %}{{ data.seo_keywords }}{% else %}{{ data.name }}{% endif %}">
{% endblock %}
{% block content %}

<section class="content">
    <div class="serach_line serach_line-page">
        <div class="wrapper">
            <form action="" class="serach_line__form" onsubmit="return false">
                <input id="serach_line" name="search" type="text" placeholder="Поиск">
            </form>
            <div class="header_search__list"></div>
        </div>
    </div>
    <div class="main_filter">
        <div class="wrapper">
            <div class="main_filter__title">Фильтр</div>
        </div>
        <form class="filter">
            <div class="close close-filter"></div>
            <div class="filter__row filter__row-top">
                <div class="filter__fltr">Фильтры:</div>
                <div class="filter__col">
                    <div class="filter__col_col">
                        <div class="filter__title active">Тип</div>
                    </div>
                    <div class="filter_switch" style="opacity: 0;">
                        <div class="filter_switch__left"></div>
                        <div class="filter_switch__right">
                            <div class="filter_switch__radio">
                                <input id="filter_1" value="filter_1" name="filter" type="radio" checked="checked">
                                <label for="filter_1">интерьер</label>
                            </div>
                            <div class="filter_switch__radio">
                                <input id="filter_2" value="filter_2" name="filter" type="radio">
                                <label for="filter_2">натура</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="filter__col">
                    <div class="filter__title">Помещение</div>
                </div>
                <div class="filter__col">
                    <div class="filter__title">Стиль</div>
                </div>
            </div>
            <div class="filter__row filter__row-big">
                <div class="filter__col filter__col-col active locations_type">
                    {% for t in locations_type %}
                        <div class="filter__checkbox">
                            <input id="loc_type_{{ t.0 }}_" value="{{ t.0 }}" name="loc_type" type="checkbox">
                            <label for="loc_type_{{ t.0 }}_">{{ t.1 }}</label>
                        </div>
                    {% endfor %}
                </div>
                <div class="filter__col filter__col-col rooms_type">
                    {% for t in rooms_type %}
                        <div class="filter__checkbox">
                            <input id="room_{{ t.0 }}_" value="{{ t.0 }}" name="room" type="checkbox">
                            <label for="room_{{ t.0 }}_">{{ t.1 }}</label>
                        </div>
                    {% endfor %}
                </div>
                <div class="filter__col filter__col-col styles_type">
                    {% for t in styles_type %}
                        <div class="filter__checkbox">
                            <input id="styles_type_{{ t.0 }}_" value="{{ t.0 }}" name="room" type="checkbox">
                            <label for="styles_type_{{ t.0 }}_">{{ t.1 }}</label>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="filter__row">
                <div class="filter__col filter__col-double"></div>
                <div class="filter__col filter__col-clear">
                    <div class="filter__button filter__button-clear">сбросить ×</div>
                    <div class="filter__button filter__button-watch">смотреть →</div>
                </div>
            </div>
        </form>
    </div>
    <!--<div class="wrapper">-->
        <!--<div class="search_res">-->
            <!--<div class="search_res__txt">Фильтры поиска: </div>-->
            <!--<div class="search_res__result">Квартира ×</div>-->
        <!--</div>-->
    <!--</div>-->
    <div class="wrapper wrapper-search">
        <div class="search__wrp">
            {% for l in locs %}
                <a href="{% url 'main:card' l.alias %}" class="search__el">
                    <div class="search__img" style="background-image: url(//locationbook.ru{{ l.get_first_item.image.url }});"></div>
                    <div class="search__desc">
                        <div class="search__title">{{ l.name }}</div>
                        <div class="search__counter">{% if l.number %}{{ l.number }}{% else %}{{ l.pk }}{% endif %}</div>
                        <div class="search__row search__row-border">{{ l.get_addres_display }}</div>
                        <div class="search__row">120 м2</div>
                    </div>
                </a>
            {% endfor %}
        </div>
        <div class="search_nav">
            <div class="search_nav__help">{{ locs.start_index }}—{{ locs.end_index }} из {{ locations|length }} локаций</div>
            {% if locs.has_previous %}
            <a href="?page={{ pag }}{{ locs.previous_page_number }}{{dop_url}}"><div class="search_nav__next">← назад</div></a>
            {% endif %}
            <div class="search_nav__navs">
                {% for pag in locs.paginator.page_range %}
                    {% if pag == locs.number %}
                        <div class="search_nav__nav">{{ pag }}</div>
                    {% else %}
                        <a href="?page={{ pag }}{{dop_url}}"><div class="search_nav__nav">{{ pag }}</div></a>
                    {% endif %}
                {% endfor %}
            </div>
            {% if locs.has_next %}
            <a href="?page={{ pag }}{{ locs.next_page_number }}{{dop_url}}"><div class="search_nav__next">далее →</div></a>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

{% block more_js %}
<script>
    $(document).ready(function () {
        $(function() {
            $('.serach_line .serach_line__form input[name=search]').autocomplete({
                source: "/get_fields/",
                minLength: 2,
                select: function( event, ui ) {
                    log( ui.item ?
                        "Выбрано: " + ui.item.value + " aka " + ui.item.id :
                        "Нет ничего подходящего " + this.value );
                }
            }).on( "autocompletesearch", function( event, ui ) {
                $('.serach_line .header_search__list').html('')
            })
            .data( "autocomplete" )._renderItem = function( ul, item ) {
                return $.when($('<div class="header_search__el"></div>')
                                    .data( "item.autocomplete", item )
                                    .append( '<a href="/location-base/' + item.alias + '/" class="catalog-item">' + item.name + '</a>' )
                                    .appendTo('.serach_line .header_search__list')).then($('.serach_line .header_search__list > div').length ? $('.serach_line .header_search__list').addClass('active') : $('.serach_line .header_search__list').removeClass('active'))
            }
        })
    })
</script>
{% endblock %}

templates/sitemap_xml.html
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    {% for u in urls %}
    <url>
        <loc>{{ u }}</loc>
        <changefreq>daily</changefreq>
        <priority>0.5</priority>
    </url>
    {% endfor %}
</urlset>

templates/textpage.html
{% extends "base.html" %}
{% block seo_titles %}
    <title>{% if data.seo_title %}{{ data.seo_title }}{% else %}{{ data.name }}{% endif %}</title>
    <meta name="description" content="{% if data.seo_description %}{{ data.seo_description }}{% else %}{{ data.name }}{% endif %}">
    <meta name="keywords" content="{% if data.seo_keywords %}{{ data.seo_keywords }}{% else %}{{ data.name }}{% endif %}">
{% endblock %}

{% block content %}

  <div class="wrapper">
    <div class="breadcrumbs">
      <a href="/">Главная</a> /
      <span>{{ data.name }}</span>
    </div>

    <article class="txt">
      <h1 class="txt__h1">{{ data.name }}</h1>
      <div class="txt__text">
        {{ data.content|safe }}  
      </div>
    </article>
  </div>
  
{% endblock %}